events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new', views.CreateView.as_view(), name='create'),
    path('detail/<int:pk>', views.DetailView.as_view(), name='detail'),
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
    path('descending/', views.DescendingView.as_view(), name='descending'),
    path('search_results/', views.DescriptionSearchView.as_view(), name='search_results'),
    path('chart', views. ChartView, name='chart'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('events.urls')),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register')
]

events/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Event(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    description = models.CharField(max_length=200)
    date = models.DateTimeField('date')
    created_datetime = models.DateTimeField(auto_now_add=True)
    last_updated_datetime = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return str(self.date_diff) + " days until " + self.description

    @property
    def date_diff(self):
        today = timezone.now()
        return (self.date - today).days + 1

    @property
    def get_date_only(self):
        return self.date.date()

users/models.py
from django.db import models

# Create your models here.

events/forms.py
from django import forms
from .models import Event

class DateInput(forms.DateInput):
    input_type = 'date'

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['description', 'date']
        widgets = {
            'date': DateInput(),
        }

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs = {
            'class': 'form-control mb-3',
            'placeholder': 'description',
        }
        self.fields['date'].widget.attrs = {
            'class': 'form-control mb-3',
        }

events/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from .models import Event
from .forms import EventForm

class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    template_name = 'events/index.html'
    model = Event

    def get_queryset(self):
        """Return all events created by current user in ascending order."""
        return Event.objects.filter(author=self.request.user).order_by('date')

class CreateView(LoginRequiredMixin, generic.edit.CreateView):
    login_url = '/login/'
    template_name = 'events/create.html'
    model = Event
    form_class = EventForm
    success_url = reverse_lazy('events:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = '/login/'
    template_name = 'events/detail.html'
    model = Event

    def get_queryset(self):
        """Return event created by current user."""
        return Event.objects.filter(author=self.request.user)

class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    login_url = '/login/'
    template_name = 'events/update.html'
    model = Event
    form_class = EventForm
    success_url = reverse_lazy('events:index')

class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    login_url = '/login/'
    template_name = 'events/delete.html'
    model = Event
    success_url = reverse_lazy('events:index')

class DescendingView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    template_name = 'events/index.html'
    model = Event

    def get_queryset(self):
        """Return all events created by current user in descending order."""
        return Event.objects.filter(author=self.request.user).order_by('-date')

class DescriptionSearchView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    template_name = 'events/index.html'
    model = Event

    def get_queryset(self):
        """Return events created by current user that contains the query in ascending order."""
        query = self.request.GET.get('q')
        if query:
            object_list = (Event.objects
                            .filter(author=self.request.user)
                            .filter(description__icontains=query)
                            .order_by('date'))
        else:
            object_list = Event.objects.none()
        return object_list

def ChartView(request):
    jan_events_count = Event.objects.filter(author=request.user).filter(date__month='1').count()
    feb_events_count = Event.objects.filter(author=request.user).filter(date__month='2').count()
    mar_events_count = Event.objects.filter(author=request.user).filter(date__month='3').count()
    apr_events_count = Event.objects.filter(author=request.user).filter(date__month='4').count()
    may_events_count = Event.objects.filter(author=request.user).filter(date__month='5').count()
    jun_events_count = Event.objects.filter(author=request.user).filter(date__month='6').count()
    jul_events_count = Event.objects.filter(author=request.user).filter(date__month='7').count()
    aug_events_count = Event.objects.filter(author=request.user).filter(date__month='8').count()
    sep_events_count = Event.objects.filter(author=request.user).filter(date__month='9').count()
    oct_events_count = Event.objects.filter(author=request.user).filter(date__month='10').count()
    nov_events_count = Event.objects.filter(author=request.user).filter(date__month='11').count()
    dec_events_count = Event.objects.filter(author=request.user).filter(date__month='12').count()

    events_per_month = [
        jan_events_count,
        feb_events_count,
        mar_events_count,
        apr_events_count,
        may_events_count,
        jun_events_count,
        jul_events_count,
        aug_events_count,
        sep_events_count,
        oct_events_count,
        nov_events_count,
        dec_events_count
    ]

    context = {'events_per_month': events_per_month}
    return render(request, 'events/chart.html', context)

users/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
class RegisterView(SuccessMessageMixin, generic.edit.CreateView):
    template_name = 'users/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    success_message = "New user created successfully"
    

events/templates/events/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script defer src="https://unpkg.com/htmx.org@1.7.0"></script>
    <script defer src="{% static 'main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.8.0/dist/chart.min.js"></script>
</head>
<body>
    {% include 'events/nav.html' %}
    {% block content %}
    {% endblock %}
    {% include 'events/modal.html' %}
</body>
</html>

events/templates/events/chart.html
{% extends 'events/base.html' %}

{% block content %}
<div class="container">
    <canvas id="monthChart"></canvas>
</div>

<script>
    const labels = [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December'
    ];

    const data = {
        labels: labels,
        datasets: [{
            label: 'Events per month',
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: [{% for month in events_per_month %} '{{ month }}', {% endfor %}],
        }]
    };

    const config = {
        type: 'bar',
        data: data,
        options: {}
    };
</script>

<script>
    const myChart = new Chart(
        document.getElementById('monthChart'),
        config
    );
</script>
{% endblock %}

events/templates/events/create.html
{% extends 'events/base.html' %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {% include "events/form.html" %}
        <input class="btn btn-outline-primary" type="submit" value="submit">
        <a href="{% url 'events:index' %}" class="btn btn-outline-dark">return</a>
    </form>
</div>
{% endblock %}

events/templates/events/delete.html
{% extends "events/base.html" %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="alert alert-danger">Are you sure you want to delete event "{{ object.description }}"?</div>
        <input class="btn btn-outline-primary" type="submit" value="submit">
        <a href="{% url 'events:index' %}" class="btn btn-outline-dark">return</a>
    </form>
</div>
{% endblock %}

events/templates/events/detail.html
<div class="modal-content">
    <div class="modal-body">
        <ul class="list-group">
            <li class="list-group-item">{{ object }}</li>
            <li class="list-group-item">Date: {{ object.get_date_only }}</li>
            <li class="list-group-item">Author: {{ object.author }}</li>
            {% if object.last_updated_datetime|date:'m-d-Y H:i:s' == object.created_datetime|date:'m-d-Y H:i:s' %}
                <li class="list-group-item">Created: {{ object.created_datetime|date:'N j, Y H:i:s' }}</li>
            {% else %}
                <li class="list-group-item" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Created: {{ object.created_datetime }}">Updated: {{ object.last_updated_datetime|date:'N j, Y H:i:s' }}</li>
            {% endif %}
        </ul>
    </div>
    <div class="modal-footer">
        <a href="{% url 'events:update' event.id %}" class="btn btn-outline-success">edit</a>
        <a href="{% url 'events:delete' event.id %}" class="btn btn-outline-danger">delete</a>
        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">return</button>
    </div>
</div>

events/templates/events/filter_btn.html
{% if object_list %}
<div class="d-flex flex-row-reverse">
    <div class="dropdown mb-2">
        <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">Sort</button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            {% if request.path == '/' %}
                <li>
                    <a href="{% url 'events:index' %}" class="dropdown-item active" id="ascending-btn">Ascending</a>
                </li>
                <li>
                    <a href="{% url 'events:descending' %}" class="dropdown-item" id="descending-btn">Descending</a>
                </li>
            {% elif request.path == '/descending/' %}
                <li>
                    <a href="{% url 'events:index' %}" class="dropdown-item" id="ascending-btn">Ascending</a>
                </li>
                <li>
                    <a href="{% url 'events:descending' %}" class="dropdown-item active" id="descending-btn">Descending</a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="me-auto">
        <a href="{% url 'events:chart' %}" class="btn btn-outline-primary">Events per month</a> 
    </div>
</div>
{% endif %}

events/templates/events/form.html
{% for field in form %}
<!-- <div class="ms-auto mb-3 row">
    <label class="col-sm-2 col-form-label">{{ field.label_tag }}</label>
    <div class="col-6">{{ field }}</div>
</div> -->
    {{ field.label_tag }}
    {{ field }}
{% endfor %}

events/templates/events/index.html
{% extends "events/base.html" %}

{% block content %}
<div class="container">
    {% include "events/filter_btn.html" %}
    <div class="list-group">
        {% for event in object_list %}
            <button type="button" hx-get="{% url 'events:detail' event.id %}" hx-target="#dialog" class="list-group-item list-group-item-action">{{ event }}</button>
        {% endfor %}
    </div>
</div>
{% endblock %}

events/templates/events/modal.html
<div id="modal" class="modal fade">
    <div id="dialog" class="modal-dialog modal-dialog-centered" hx-target="this"></div>
</div>

events/templates/events/nav.html
<nav class="navbar sticky-top navbar-expand-lg bg-light mb-2">
    <div class="container-fluid">
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="navbar-brand" href="{% url 'events:index' %}">X days until</a>
                </li>
            </ul>
        </div>

        {% if user.is_authenticated %}
        <a href="{% url 'events:create' %}" class="btn btn-outline-primary">create</a> 
        <form method="GET" action="/search_results/">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search" name="q" value="{{ request.GET.q }}">
                <input class="btn btn-outline-primary" type="submit" value="submit">
            </div>
        </form>
        {% endif %}
        
        <div>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Logged in as {{ user.username }} | </span>
                        <a href="/logout" class="btn btn-outline-secondary">logout</a>
                    </li>
                {% elif request.path != '/login/' %}
                    <li class="nav-item">
                        <a href="/login" class="btn btn-outline-secondary">login</a>
                    </li>
                {% elif request.path != '/users/register' %}
                    <li class="nav-item">
                        <a href="/users/register" class="btn btn-outline-secondary">register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

events/templates/events/update.html
{% extends 'events/base.html' %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {% include "events/form.html" %}
        <input class="btn btn-outline-primary" type="submit" value="submit">
        <a href="{% url 'events:delete' object.id %}" class="btn btn-outline-danger">delete</a>
        <a href="{% url 'events:index' %}" class="btn btn-outline-dark">return</a>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends "events/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <form method="post" class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-outline-success" type="submit" value="register">
    </form>
</div>
{% endblock %}